export { default as Hero } from './Hero'
export { default as Services } from './Services'
export { default as Technology } from './Technology'
export { default as Portfolio } from './Portfolio'
export { default as About } from './About'
export { default as Contact } from './Contact'
